server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dancesphere_dancer
    username: postgres
    password: mypassword
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update  # Para desarrollo: crea/actualiza tablas
    show-sql: true      # Muestra las consultas en logs
