spring:
  data:
    mongodb:
      uri: mongodb+srv://peter:FHrRQp9sJIOA0CTF@cluster0-prueba.kuwmb.mongodb.net/dancesphere
      # Puedes agregar las opciones adicionales que necesites
      # username: root
      # password: rootpass
      # host: localhost
      # port: 27017

logging:
  level:
    org.springframework: DEBUG
